# axper

name: axper
parent: default

matches:
  - trigger: ":ayo"
    replace: "այո"

  - trigger: ":axper"
    replace: "ախպեր"

  - trigger: ":che"
    replace: "չէ"

  - trigger: ":eh"
    replace: "է"

  - trigger: ":inchgachga"
    replace: "Ի՞նչ կա չկա"

  - trigger: ":gam"
    replace: "կամ"

  - trigger: ":hedo"
    replace: "հետո"

  - trigger: ":hima"
    replace: "Հիմա"

  - trigger: ":kichme"
    replace: "քիչ մը"

  - trigger: ":merci"
    replace: "մերսի"

  - trigger: ":paits"
    replace: "բայց"

  - trigger: ":parev"
    replace: "բարեւ"

  - trigger: ":Parev"
    replace: "Բարեւ"

  - trigger: ":pariluis"
    replace: "բարի լոյս"

  - trigger: ":teh"
    replace: "թե"

  - trigger: ":voch"
    replace: "ոչ"
